// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebDownload.Server.Models;

public partial class MediaMenu
{
    public Guid RecordId { get; set; }
    public string Menu { get; set; } = "";
    public DateTime Datetime { get; set; }
    public ICollection<MediaFolder> MediaFolders { get; set; } = new List<MediaFolder>();
}