// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebDownload.Server.Models;

public partial class MediaSubtitle
{
    public Guid RecordId { get; set; }
    public Guid MediaMetaDataRecordId { get; set; }
    public string FileName { get; set; } = "";
    public string? Label { get; set; }
    public string? Language { get; set; }
    public bool IsDefault { get; set; }

    public MediaTrack MediaMetaDataRecord { get; set; } = null!;
}