// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebDownload.Server.Models;

public partial class MediaTrack
{
    public Guid RecordId { get; set; }
    public Guid FolderId { get; set; }
    public string FileName { get; set; } = "";
    public string? Title { get; set; }

    public MediaFolder Folder { get; set; } = null!;
    public ICollection<MediaSubtitle> MediaSubtitles { get; set; } = new List<MediaSubtitle>();
}