// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebDownload.Server.Models;

public partial class MediaFolder
{
    public Guid RecordId { get; set; }
    public Guid MenuId { get; set; }
    public Guid? ParentFolderId { get; set; }
    public string Name { get; set; } = "";
    public string? RootPath { get; set; }
    public string? CoverImagePath { get; set; }
    public DateTime Datetime { get; set; }

    public MediaMenu Menu { get; set; } = null!;
    public MediaFolder? ParentFolder { get; set; }
    public ICollection<MediaFolder> InverseParentFolder { get; set; } = new List<MediaFolder>();
    public ICollection<MediaTrack> MediaTracks { get; set; } = new List<MediaTrack>();
}